# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "money"
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["caleon"]
  s.date = "2012-10-22"
  s.description = "    This is a representation of Money (and various arbitrary currencies),\n    created with usage within the Rails framework in mind, although it can\n    stand alone as long as you are okay with including ActiveModel for\n    validations and a few ActiveSupport helpers (although those can be handled\n    differently if there is enough desire to decouple this from those\n    dependencies).\n\n    Its greatest utility will come when used with ActiveRecord objects\n    stored as database rows, where combined with ActiveRecord's `composed_of`\n    statement, you are able to separate the tedious money-related logic\n    within your classes which utilize the abstraction.\n\n    Out of convenience, this is written for Ruby 1.9, although there shouldn't\n    be many changes required ot make this 1.8 compatible. RCov is not listed\n    as a dependency since 1.9 setups should use simplecov instead.\n"
  s.email = "caleon@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/money.rb",
    "spec/money_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/caleon/money"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Ruby class for representing Money with currencies for use with Rails and ActiveRecord"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.11"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<activemodel>, [">= 3.1.0"])
      s.add_development_dependency(%q<activesupport>, [">= 3.1.0"])
      s.add_development_dependency(%q<significance>, ["~> 0.1.4"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.11"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<activemodel>, [">= 3.1.0"])
      s.add_dependency(%q<activesupport>, [">= 3.1.0"])
      s.add_dependency(%q<significance>, ["~> 0.1.4"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.11"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<activemodel>, [">= 3.1.0"])
    s.add_dependency(%q<activesupport>, [">= 3.1.0"])
    s.add_dependency(%q<significance>, ["~> 0.1.4"])
  end
end

